package com.onethefull.dasomtutorial.ui.learn

/**
 * Created by sjw on 2021/11/15
 */
enum class LearnStatus {
    START,
    CALL_DASOM,
    CALL_GEINIE,
    CALL_SOS,
    RETRY,
    HALF,
    COMPLETE,
    END,


    QUIZ_SHOW,
    QUIZ_START,
    QUIZ_ERROR,

//    CHECK_MEAL_EXTRACT_CATEGORY
    EXTRACT_CATEGORY,
    EXTRACT_TIME,
    SHOW,
    SLEEP,
    WAKEUP,

    START_TUTORIAL_1,
    START_TUTORIAL_1_1,
    START_TUTORIAL_1_2,
    START_TUTORIAL_1_3,

    START_TUTORIAL_2,
    START_TUTORIAL_3,
    START_TUTORIAL_3_1,
    START_TUTORIAL_3_2,
    START_TUTORIAL_3_3,
    START_TUTORIAL_3_4,
    START_TUTORIAL_3_5,

    START_TUTORIAL_4,
    START_TUTORIAL_4_1,
    START_TUTORIAL_4_2,

    START_DASOMTALK_TUTORIAL_1,
    START_DASOMTALK_TUTORIAL_1_1,
    START_DASOMTALK_TUTORIAL_1_2,

    START_DASOMTALK_VIDEO,
    START_DASOMTALK_TUTORIAL_2,
    START_DASOMTALK_TUTORIAL_2_1,
    START_DASOMTALK_TUTORIAL_2_2,

    START_VIDEOCALL_TUTORIAL_1,
    START_VIDEOCALL_TUTORIAL_1_1,
    START_VIDEOCALL_TUTORIAL_1_2,

    START_VIDEOCALL_VIDEO,
    START_VIDEOCALL_TUTORIAL_2,

    START_SOS_TUTORIAL_1,
    START_SOS_TUTORIAL_1_1,
    START_SOS_TUTORIAL_1_2,
    START_SOS_VIDEO,
    START_SOS_TUTORIAL_2,

    START_MEDICATION_TUTORIAL_1,
    START_MEDICATION_TUTORIAL_1_1,
    START_MEDICATION_TUTORIAL_1_2,

    START_MEDICATION_VIDEO,
    START_MEDICATION_TUTORIAL_2,

    START_RADIO_TUTORIAL_1,
    START_RADIO_VIDEO,
    START_RADIO_TUTORIAL_2,

    END_TUTORIAL,
    END_TUTORIAL_1_1,
    END_TUTORIAL_1_2_1,
    END_TUTORIAL_1_2_2,
    END_TUTORIAL_1_3,
    END_TUTORIAL_1_4
}