package com.onethefull.dasomtutorial.ui.learn

/**
 * Created by sjw on 2021/11/15
 */
enum class LearnStatus {
    START,
    CALL_DASOM,
    CALL_GEINIE,
    CALL_SOS,
    RETRY,
    HALF,
    COMPLETE,
    END,


    QUIZ_SHOW,
    QUIZ_START,
    QUIZ_ERROR,

    //    CHECK_MEAL_EXTRACT_CATEGORY
    EXTRACT_CATEGORY,
    EXTRACT_CATEGORY_1,
    EXTRACT_TIME,
    SHOW,
    SLEEP,
    WAKEUP,
    FINISH,


    // 다솜 전시회용 튜토리얼 안내
    START_TUTORIAL_1,
    START_TUTORIAL_1_1,
    START_TUTORIAL_1_2,
    START_TUTORIAL_1_3,

    START_TUTORIAL_2,
    START_TUTORIAL_3,
    START_TUTORIAL_3_1,
    START_TUTORIAL_3_2,
    START_TUTORIAL_3_3,
    START_TUTORIAL_3_4,
    START_TUTORIAL_3_5,

    START_TUTORIAL_4,
    START_TUTORIAL_4_1,
    START_TUTORIAL_4_2,

    START_DASOMTALK_TUTORIAL_1,
    START_DASOMTALK_TUTORIAL_1_1,
    START_DASOMTALK_TUTORIAL_1_2,

    START_DASOMTALK_VIDEO,
    START_DASOMTALK_TUTORIAL_2,
    START_DASOMTALK_TUTORIAL_2_1,
    START_DASOMTALK_TUTORIAL_2_2,

    START_VIDEOCALL_TUTORIAL_1,
    START_VIDEOCALL_TUTORIAL_1_1,
    START_VIDEOCALL_TUTORIAL_1_2,

    START_VIDEOCALL_VIDEO,
    START_VIDEOCALL_TUTORIAL_2,

    START_SOS_TUTORIAL_1,
    START_SOS_TUTORIAL_1_1,
    START_SOS_TUTORIAL_1_2,
    START_SOS_VIDEO,
    START_SOS_TUTORIAL_2,

    START_MEDICATION_TUTORIAL_1,
    START_MEDICATION_TUTORIAL_1_1,
    START_MEDICATION_TUTORIAL_1_2,

    START_MEDICATION_VIDEO,
    START_MEDICATION_TUTORIAL_2,

    START_RADIO_TUTORIAL_1,
    START_RADIO_VIDEO,
    START_RADIO_TUTORIAL_2,

    END_TUTORIAL,
    END_TUTORIAL_1_1,
    END_TUTORIAL_1_2_1,
    END_TUTORIAL_1_2_2,
    END_TUTORIAL_1_3,
    END_TUTORIAL_1_4,

    START_TUTORIAL_MV,

    //광고
    START_AD_WALMART,
    START_AD_UBER,
    START_AD_RANDOM,

    SPEAKING_1,
    SPEAKING_2,
    LISTENING_1,
    LISTENING_2,
    FINISH_1,
    FINISH_2,
    DONE_1,
    DONE_2,

    // 리뉴얼 취침, 기상 튜토리얼
    CHECK_SLEEP_TIME,
    CHECK_WAKEUP_TIME,
    CONFIRM_SLEEP_TIME,
    CONFIRM_WAKEUP_TIME,
    SKIP_SLEEP_CHECK,
    SKIP_WAKEUP_CHECK,


    // 리뉴얼 식사 튜토리얼
    HAS_MEAL_START,
    HAS_MEAL_A_1,
    HAS_MEAL_A_2,
    HAS_MEAL_A_3,

    HAS_MEAL_A_5,
    HAS_MEAL_A_6,
    HAS_MEAL_A_8,
    HAS_MEAL_A_9,
    HAS_MEAL_A_10,
    HAS_MEAL_A_11,

    HAS_MEAL_FINISH,
    HAS_MEAL_B_1,
    HAS_MEAL_B_2,
    HAS_MEAL_B_3,
    HAS_MEAL_B_4,
    HAS_MEAL_B_5,

    // 리뉴얼 기상 튜토리얼
    HAS_WAKEUP_START,
    HAS_WAKEUP_A_1,
    HAS_WAKEUP_A_2,
    HAS_WAKEUP_A_3,

    HAS_WAKEUP_B_1,

    HAS_WAKEUP_SLEEP_END,

    // 리뉴얼 취침 튜토리얼
    HAS_SLEEP_START,
    HAS_SLEEP_A_1,
    HAS_SLEEP_A_2,
    HAS_SLEEP_A_3,
    HAS_SLEEP_A_4,
    HAS_SLEEP_A_5,

    HAS_SLEEP_B_1,
    HAS_SLEEP_B_2,
    HAS_SLEEP_B_3,

}